---


- name: "Installing packages"
  yum:
    name: "{{ packages }}"
    state: installed
  vars:
    packages:
    - java
    - zip
    - unzip
  become: yes

- name: Installing stable chrome
  shell: 'curl https://intoli.com/install-google-chrome.sh | bash'

- stat:
    path: ~/chromedriver
  register: chromedriver_exist

- name: Find latest version of chrome driver
  shell: 'curl "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"'
  register: chrome_version

- fail:
    msg: "Could not lookup latest version for chrome driver from https://chromedriver.storage.googleapis.com/LATEST_RELEASE"
  when: chrome_version is failed

- name: Downloading chromedriver
  shell: "wget https://chromedriver.storage.googleapis.com/{{ chrome_version..stdout }}/chromedriver_linux64.zip"
  when: chromedriver_exist is defined and chromedriver_exist.stat.exists == false

- name: Unzip chromedriver
  shell: 'unzip chromedriver_linux64.zip'
  when: chromedriver_exist is defined and chromedriver_exist.stat.exists == false

- name: Moving chromedriver to usr bin
  shell: 'cp chromedriver /usr/bin'
  when: chromedriver_exist is defined and chromedriver_exist.stat.exists == false
  become: yes
- name: Moving chromedriver to usr local bin
  shell: 'cp chromedriver /usr/local/bin'
  when: chromedriver_exist is defined and chromedriver_exist.stat.exists == false
  become: yes
